
name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        sudo: false
        limit-access-to-actor: true
        timeout-minutes: 30

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    outputs:
      tag-name: ${{ steps.semantic.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install
        run: npm install
      - name: semantic
        id: semantic
        run: npx semantic-release -t \${version} --debug
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
