
#name: Publish
#
#on:
#  workflow_run:
#    workflows: ["Test"]
#    types:
#      - completed
#
#jobs:
#  setup:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [14.x]
#    outputs:
#      tag-name: ${{ steps.semantic.outputs.TAG_NAME }}
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#      - name: install
#        run: npm install
#      - name: semantic
#        id: semantic
#        run: npx semantic-release -t \${version}
#        env:
#          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
#          NPM_TOKEN : ${{ secrets.NPM_TOKEN }}
